### ISSUE TITLE
下拉刷新，页面默认不是白色，会把导航栏隐藏的白色拉下来，能否自定义颜色呢

### ISSUE THREAD

**Issue by wweihua** [lingxiaoyi/navigation-bar#11]
下拉刷新，页面默认不是白色，会把导航栏隐藏的白色拉下来，能否自定义颜色呢？
如图，页面背景色非白色，下拉出现导航栏隐藏的白色部分。
![KJ6rtA.jpg](https://s2.ax1x.com/2019/10/23/KJ6rtA.jpg)

**Comment by lingxiaoyi** [comment]
这个应该不是导航栏颜色吧,你试下这三个属性 
backgroundColor: '#f8f8f8',
    backgroundColorTop: '#084709',
    backgroundColorBottom: '#f8f8f8'
导航栏背景色可以随便修改的

**Comment by wweihua** [comment]
> 这个应该不是导航栏颜色吧,你试下这三个属性
> backgroundColor: '#f8f8f8',
> backgroundColorTop: '#084709',
> backgroundColorBottom: '#f8f8f8'
> 导航栏背景色可以随便修改的

**Comment by wweihua** [comment]
> > 这个应该不是导航栏颜色吧,你试下这三个属性
> > backgroundColor: '#f8f8f8',
> > backgroundColorTop: '#084709',
> > backgroundColorBottom: '#f8f8f8'
> > 导航栏背景色可以随便修改的

在这个例子上测试的，页面增加下拉刷新，确实下拉出来的部分是白色的，和页面设置的背景颜色不一致

**Comment by wweihua** [comment]
![KJ5l7V.jpg](https://s2.ax1x.com/2019/10/23/KJ5l7V.jpg)

**Comment by lingxiaoyi** [comment]
backgroundColorTop: '#084709'

**Comment by wweihua** [comment]
好的，我晚点试试，谢谢
