### ISSUE TITLE
Redmi 6 Pro 显示有问题

### ISSUE THREAD

**Issue by fanyanbo** [lingxiaoyi/navigation-bar#4]
![image](https://user-images.githubusercontent.com/19405107/65041128-96c84e00-d988-11e9-8055-abd5c69322dd.png)

调试基础库：2.8.2

**Comment by lingxiaoyi** [comment]
我去找一下这个手机  不太好找啊,你扫一下我的小程序,也会出现问题吗?

**Comment by fanyanbo** [comment]
![image](https://user-images.githubusercontent.com/19405107/65098002-7a182e80-d9f9-11e9-8d7c-fa3e6b095906.png)
这个正常

**Comment by lingxiaoyi** [comment]
我在申请这款机子了,尽快得到测试结果回复你

**Comment by lingxiaoyi** [comment]
![image](https://user-images.githubusercontent.com/18524956/65103411-c155ed80-da00-11e9-9e85-d27cfc1f2eca.png)

**Comment by lingxiaoyi** [comment]
![image](https://user-images.githubusercontent.com/18524956/65103428-d29efa00-da00-11e9-89e2-eb7d6b1d8558.png)

**Comment by lingxiaoyi** [comment]
你的问题我这里没出现...我是在testin云测平台上测的,你要不在调试一下?我这里真找不到这款真机...

**Comment by lingxiaoyi** [comment]
![image](https://user-images.githubusercontent.com/18524956/65103522-14c83b80-da01-11e9-85d1-cb2bd605a252.png)

**Comment by fanyanbo** [comment]
![image](https://user-images.githubusercontent.com/19405107/65110898-88237a80-da0c-11e9-8357-7d5b0862e1d5.png)

开发者工具-真机调试 打印如上，胶囊rect.top: 8，statusBarHeight: 33，gap = rect.top - systemInfo.statusBarHeight; gap为-25

**Comment by lingxiaoyi** [comment]
rect.top是胶囊的top位置,8的话说明没有加上statusBarHeight的高度.不清楚为什么会出现这样的问题.

**Comment by lingxiaoyi** [comment]
怀疑是不是其他问题导致的,我用的那个云测试也是远程真机测试的,你试试升级个系统或者关了wifi,或者其他途径解决一下

**Comment by fanyanbo** [comment]
升级微信后解决了，之前说错了，之前微信版本7.0.0，基础版本库(SDKVersion:2.5.2)，升级后微信版本7.0.6，基础版本库(SDKVersion:2.8.3)
