### ISSUE TITLE
ios平台上外层采用position:fiexed, z-index无效

### ISSUE THREAD

**Issue by yicm** [lingxiaoyi/navigation-bar#6]
- 基础调试库版本： 2.8.3
- 微信都是当前最新版本

wxml:

```
<view class="search">
    <navBar searchBar="{{true}}" background="{{searchBGColor}}"  bindsearch='search' />
</view>
```

wxss:

```
.search {
    margin-bottom: 0;
    padding-bottom: 0;
    z-index: 9999;   /* z-index 设置值超过navBar的最大z-index值 */
    position: fixed;
}
```

开发者工具预览都是正确的，真机(iphone xr/ipad pro)就不行了，大佬有测试过吗？

**开发者平台调试效果：**

![开发者工具](https://user-images.githubusercontent.com/18110379/65383694-8549c200-dd4b-11e9-92f8-38772ae02325.png)

**真机效果：**

![真机](https://user-images.githubusercontent.com/18110379/65383770-b5de2b80-dd4c-11e9-8a6b-26d36acabb26.png)

ps: android真机是ok的。

**Comment by lingxiaoyi** [comment]
navBar 默认的配置也不出来吗?不要用你的.search设置

**Comment by yicm** [comment]
默认配置有，但是我的目的是想有Swiper的背景图片

**Comment by lingxiaoyi** [comment]
Swiper的背景图片和导航条有关系吗,你要放哪里?

**Comment by yicm** [comment]
``` 
        <!--  搜索框固定在顶部，下层是Swpier，也就是navBar的背景是共用Spwier的 -->
        <view class="search">
            <navBar searchBar="{{true}}" background="{{searchBGColor}}" bindsearch='search' />
        </view>
        <!-- 头部背景区 -->
        <view class="header-logo">
            <swiper catchtap='onSwiperTap' class="swiper" 
        ......
```
如上面的开发者平台效果截图所示。

**Comment by lingxiaoyi** [comment]
那你直接把头部北背景色设置透明不行吗

**Comment by yicm** [comment]
就是啥都不设置吗？`background=""` 这样？这跟设置background没关系，是设置Swpier的位置，跟`search`css class有关，Swpier会在navBar的下面，而不是与最顶部对齐了。
![image](https://user-images.githubusercontent.com/18110379/65384108-e2944200-dd50-11e9-9115-58ee345b70eb.png)

**Comment by lingxiaoyi** [comment]
background 设置rgba(0,0,0,0)试试

**Comment by yicm** [comment]
额 目的不是navBar的背景，这是次要的，主要是将navBar放于顶层，共享navBar的背景。

![image](https://user-images.githubusercontent.com/18110379/65384160-60f0e400-dd51-11e9-916a-c9749dad0e82.png)

![image](https://user-images.githubusercontent.com/18110379/65384164-6817f200-dd51-11e9-8f65-195b4f5f4386.png)

**Comment by lingxiaoyi** [comment]
背景颜色和swiper图片一样?

**Comment by yicm** [comment]
对的，应该这么说，就是Swiper的图片，共享，我之前尝试过截取Swiper的上面部分图片，将其设置成背景，但是有个问题，ios平台上可以下拉的，下拉会出现一个背景区，这样就将navBar和swiper隔开了，很不好看，强迫症。。这个不是很好的办法

**Comment by lingxiaoyi** [comment]
swiper变换了 你主动修改组件里背景颜色,我明白你的意思了
https://github.com/lingxiaoyi/navigation-bar/issues/5

**Comment by lingxiaoyi** [comment]
你看这个问题,他是这么解决的

**Comment by yicm** [comment]
不是他这种，他这种还比较好控制，只是改变navBar的背景而已，还有navTextStyle的颜色。。

**Comment by lingxiaoyi** [comment]
那你好好研究一下,看看问题具体出在哪里..

**Comment by yicm** [comment]
具体动态效果可以看这个： http://note.youdao.com/noteshare?id=448e71f04c8e8bba92975730532f5374&sub=5EAB31AC1EDD46A7B5F267189D4FA108  只是真机出问题了，好来问你下，毕竟你开发了这个组件，细节比较清楚，可能哪里有影响。。

**Comment by lingxiaoyi** [comment]
![image](https://user-images.githubusercontent.com/18524956/65384488-97c8f900-dd55-11e9-92aa-85f673815a9f.png)
你那种写法实在解决不了 就把标红这行代码注释了试试

**Comment by yicm** [comment]
注释掉了，不行。。

**Comment by lingxiaoyi** [comment]
注释掉了 你那个外层元素也要去掉,我这个组件高度就这个东西撑起来的

**Comment by lingxiaoyi** [comment]
实在不行你多尝试研究一下,这种都不算什么问题,问题不一定是组件出现的,也有可能是微信自身样式显示和普通的html是不一样的

**Comment by yicm** [comment]
有可能是个bug...毕竟开发者工具仿真没有问题。。

**Comment by lingxiaoyi** [comment]
因为ios Android和开发工具用的底层代码都是不一样的,一样的嵌套组件写法,真机表现形式很可能会出现不同,这种问题最好多测试,多调试就能找到办法解决了

**Comment by yicm** [comment]
嗯 在尝试，只是目前没有多少效果。。
